"""Configuration package — feature flags and default configs."""
from .feature_flags import (
    get_all_flags,
    get_all_config,
    ENABLE_ENDPOINT_VALIDATION,
    ENABLE_CIRCUIT_BREAKER,
    ENABLE_MODEL_REGISTRY,
    ENABLE_RETRY_FAILOVER,
    ENABLE_SELF_HEALING,
    ENABLE_STRUCTURED_LOGGING,
    ENABLE_REPORT_GENERATION,
    ENABLE_ANTI_DPI_IRAN,
    ENABLE_UTLS_EVASION,
    ENABLE_IRST_ROUTING,
    ENABLE_COMPAT_PATH_FIX,
    ENABLE_TELEMETRY,
)

__all__ = [
    "get_all_flags",
    "get_all_config",
    "ENABLE_ENDPOINT_VALIDATION",
    "ENABLE_CIRCUIT_BREAKER",
    "ENABLE_MODEL_REGISTRY",
    "ENABLE_RETRY_FAILOVER",
    "ENABLE_SELF_HEALING",
    "ENABLE_STRUCTURED_LOGGING",
    "ENABLE_REPORT_GENERATION",
    "ENABLE_ANTI_DPI_IRAN",
    "ENABLE_UTLS_EVASION",
    "ENABLE_IRST_ROUTING",
    "ENABLE_COMPAT_PATH_FIX",
    "ENABLE_TELEMETRY",
]
